#
# Copyright (c) 2026 - present - Yupiik SAS - https://www.yupiik.com
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#  http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
#

services:

  statura-database:
    container_name: statura-database
    image: postgres
    environment:
      POSTGRES_DB: statura
      POSTGRES_USER: statura
      POSTGRES_PASSWORD: statura
      PGDATA: /data/postgres
    ports:
      - "5432:5432"
    restart: on-failure
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U statura" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  statura-otel-collector:
    image: otel/opentelemetry-collector-contrib:0.149.0
    container_name: otel-collector-debug
    command: [ "--config=/etc/otelcol/config.yaml" ]
    volumes:
      - ./otel-collector-config.yaml:/etc/otelcol/config.yaml:ro
    ports:
      - "4317:4317"
      - "4318:4318"
    restart: unless-stopped

  statura-health:
    container_name: statura-health
    image: ossyupiik/statura:1.0.6
    command: ["executor"]
    environment:
      STATURA_CONFIGURATIONLOCATION: "/opt/yupiik/statura/config/statura-config.json"
    volumes:
      - ./custom/postgresql-42.7.13.jar:/opt/yupiik/statura/custom/postgresql-42.7.13.jar:ro
      - ./statura-config.json:/opt/yupiik/statura/config/statura-config.json:ro
    restart: no
    depends_on:
      statura-database:
        condition: service_healthy
      statura-otel-collector:
        condition: service_started
