# assumed using minikube and local build
statura.image.pullPolicy = Never
statura.image.repository = yupiik/statura
statura.image.tag = {{project_version}}

# demo config
statura.configuration.content = {{bundlebee-inlined-file:{{bundlebee_basedir}}/placeholders/dev.checks.json}}
