#
# Copyright (c) 2026 - present - Yupiik SAS - https://www.yupiik.com
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#  http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
#

statura.name = statura
statura.namespace = statura

# service account
statura.serviceAccount.name = statura
statura.serviceAccount.automount = false
statura.serviceAccount.labels = { "app.kubernetes.io/name":"statura" }
statura.serviceAccount.annotations = {}

# secret
statura.secret.name = statura
statura.secret.labels = { "app.kubernetes.io/name":"statura" }
statura.secret.annotations = { "io.yupiik.bundlebee/putOnUpdate": "true" }
statura.secret.content = {}

# configmap
statura.configmap.name = statura
statura.configmap.labels = { "app.kubernetes.io/name":"statura" }
statura.configmap.annotations = { "io.yupiik.bundlebee/putOnUpdate": "true" }
statura.configuration.content = {}

# cronjob
statura.cronjob.name = statura
statura.cronjob.schedule = */15 * * * *
statura.cronjob.startingDeadlineSeconds = 120
statura.cronjob.concurrencyPolicy = Forbid
statura.cronjob.successfulJobsHistoryLimit = 3
statura.cronjob.failedJobsHistoryLimit = 1
statura.cronjob.backoffLimit = 2
statura.cronjob.ttlSecondsAfterFinished = 300
statura.cronjob.restartPolicy = OnFailure
statura.cronjob.labels = {"app.kubernetes.io/name":"statura"}
statura.cronjob.annotations = {}
statura.cronjob.podLabels = {"app.kubernetes.io/name":"statura"}
statura.cronjob.podAnnotations = {}
statura.cronjob.imagePullSecrets = []

# image
statura.image.repository = statura
statura.image.tag = latest
statura.image.pullPolicy = IfNotPresent

# security
statura.podSecurityContext = {\
  "runAsNonRoot": true,\
  "runAsUser": 1000,\
  "runAsGroup": 1000,\
  "fsGroup": 1000,\
  "seccompProfile": {\
    "type": "RuntimeDefault"\
  }\
}
statura.containerSecurityContext = {\
  "allowPrivilegeEscalation": false,\
  "readOnlyRootFilesystem": true,\
  "capabilities": {\
    "drop": ["ALL"]\
  },\
  "runAsNonRoot": true,\
  "runAsUser": 1000\
}

# resources
statura.resources = { \
    "requests": { \
      "cpu": "200m", \
      "memory": "256Mi" \
    }, \
    "limits": { \
      "memory": "256Mi" \
    } \
  }
statura.tmp.size = 8Mi

# scheduling
statura.nodeSelector = {}
statura.affinity = {}
statura.tolerations = []

# global labels
statura.labels = {"app.kubernetes.io/name":"statura"}
statura.annotations = {}
